hunt_the_wumpus:
	g++ -g hunt_the_wumpus.cpp caves.cpp room.cpp wumpus.cpp pits.cpp bats.cpp gold.cpp empty.cpp adventurer.cpp -o hunt_the_wumpus -g
clean:
	rm -f *.o hunt_the_wumpus                                  
