#include<iostream> 
#include<cstdlib> 
#include"monkey.hpp"

using namespace std; 

/***************************************
 *Function:		Monkey            
 *Description:        	constructor for monkey class
 *Parameters:           N/A
 *Pre-conditions:       Monkey type called 
 *Post-conditions:      N/A
 *Return:              	N/A
*****************************************/

Monkey::Monkey(){
	age = 0;
	cost = 200; 
	revenue = 3000; 
	alive = false; 
}

/***************************************
 *Function:            Monkey
 *Description:         Parameterized constructor 
 *Parameters:          age of animal, cost, revenue and alive status 
 *Pre-conditions:      Monkey type called 
 *Post-conditions:     N/A 
 *Return:              N/A
*****************************************/

Monkey::Monkey(int age, float cost, int revenue, bool alive){
	this -> age = age;
	this-> cost = cost;
	this -> revenue = revenue; 
	this ->alive =alive;
}
 
/***************************************
 *Function:            food_cost 
 *Description:         calculates the food cost for a given monkey 
 *Parameters:          N/A
 *Pre-conditions:      turn took place 
 *Post-conditions:     N/A
 *Return:              cost of one monkey 
*****************************************/

int Monkey::food_cost(){
	float multiplier = rand()%50+1;
	float multi = (multiplier/100)+.75;	
	cost = cost * multi;	
	return cost; 
} 

/***************************************
 *Function:            set_adult_status 
 *Description:         checks to see if monkey is an adult
 *Parameters:          N/A
 *Pre-conditions:      turn took place 
 *Post-conditions:     age incremented 
 *Return:              N/A
*****************************************/

void Monkey::set_adult_status(){
	if(age > 1095){
		revenue = 1500; 		
	}
}
 
/***************************************
 *Function:            get_rev
 *Description:         returns the revenue generated by the specific animal 
 *Parameters:          N/A
 *Pre-conditions:      turn took place 
 *Post-conditions:     N/A
 *Return:              int revenue 
*****************************************/

int Monkey::get_rev(){
	return this-> revenue; 
}
 
/***************************************
 *Function:            get_cost
 *Description:         returns the food cost for the animal 
 *Parameters:          N/A 
 *Pre-conditions:      function is called 
 *Post-conditions:     cost returned 
 *Return:              cost of animal 
*****************************************/

float Monkey::get_cost(){
	return this -> cost; 
}
